"""liens en sommeil : requested_at

Revision ID: d64370c64165
Revises: bc63c6d54e02
Create Date: 2026-09-21 20:53:24.006068

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd64370c64165'
down_revision: str | Sequence[str] | None = 'bc63c6d54e02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('requested_at')

    # ### end Alembic commands ###
